# Generated by Django 4.2.5 on 2023-10-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='QuizBuilder.user'),
        ),
    ]
